### ISSUE TITLE
Where to close database connection?

### ISSUE THREAD

**Issue by vylink** [apitte/core#106]
I would like to close database connection after each request. What will be the best approach? Where I can do that? Any idea?

**Comment by mabar** [comment]
Probably response and exception decorators. We will maybe add some events to Application class, but not now.

**Comment by mabar** [comment]
Related to #105 

Question is - how should be called interfaces for these before/after methods?

```php
ExampleController implements IController
{

  public function before(ApiRequest $request): ApiRequest
  {
    // some initialization
  }

  public function endpoint(ApiRequest $request, ApiResponse $response): ApiResponse
  {
    return $response
      ->withStatus(ApiResponse::S200_OK);
  }

  public function after(ApiRequest $request, ApiResponse $response): ApiResponse
  {
    // cleanup, close database connection
  }

}
```

**Comment by mabar** [comment]
@vylink I was thinking about that for a while. Do you have an use-case where you really need endpoint-specific before and after methods? Because I think this is what middlewares should do
