### ISSUE TITLE
Json:api support?

### ISSUE THREAD

**Issue by akadlec** [apitte/core#110]
Is there a way how to implement Json:Api ? https://jsonapi.org/
Right now i am using slim fw where i am able to generate own response content with jsonapi renderer

**Comment by mabar** [comment]
Yes. You can return in response whatever you want, so there is practically no problem to implement whichever specification you would like.

[apitte/negotiation](https://github.com/apitte/negotiation/blob/master/.docs/README.md) could help you with automated data transformation which will improve with implementation of #97 

Also link generator is planned, see #94 

I don't know what more can we do to support schemas like that, maybe you could present your implementation.

**Comment by akadlec** [comment]
Hmm looks interesting, will give a try. Do you know when link generator will be implemented in stable version?

**Comment by mabar** [comment]
Not sure, it's a very complicated component.

**Comment by akadlec** [comment]
@mabar ok, negotiation transformer is working, but one issue to solve. How i could get routes? According to json:api, there have to be links to other entities. Is there some way? Or i need to wait for linkgenerator?

**Comment by mabar** [comment]
Currently all endpoints with their full paths are available in Schema. https://github.com/apitte/core/blob/master/src/Schema/Schema.php

We are using [OpenApi](https://swagger.io/docs/specification/about/) (via [apitte/openapi](https://github.com/apitte/openapi)) to document our api, so never thinked about it
