### ISSUE TITLE
Add support for in='body' for @RequestParameter

### ISSUE THREAD

**Issue by BigOHenry** [apitte/core#113]
**Add support for in='body' for @RequestParameter**

@RequestParameter now supports in="path|query|header|cookie"

example from OpenApi:
![image](https://user-images.githubusercontent.com/15823552/61533747-088a2700-aa2e-11e9-9a13-3c8b0e7d31ba.png)

https://petstore.swagger.io

**Comment by mabar** [comment]
Parameters in body are implemented through `@RequestMapper`. But I am not sure if it's used in apitte/openapi

**Comment by mabar** [comment]
Mapper renamed to `@RequestBody` and implemented by Apitte v0.7-dev
