### ISSUE TITLE
Documentation: Setup (.docs/index.md)

### ISSUE THREAD

**Issue by Vlczech** [apitte/core#130]
Is really correct version of ```index.php``` in [Setup](https://github.com/apitte/core/blob/24c02299e2807ee13767bfad2037dae50f19fea2/.docs/index.md)?
```php
// www/index.php

use Apitte\Core\Application\IApplication;
use App\Bootstrap;

require __DIR__ . '/../vendor/autoload.php';

Bootstrap::boot()
	->createContainer()
	->getByType(IApplication::class)
	->run();
```

...does not work for me, old version works:

```php
$container = require __DIR__ . '/../app/bootstrap.php';
$container->getByType(Contributte\Middlewares\Application\IApplication::class)->run();

**Comment by mabar** [comment]
This is based on nette/project for nette 3
https://github.com/apitte/core/commit/24c02299e2807ee13767bfad2037dae50f19fea2
https://github.com/nette/web-project/commit/d24ef6d24109ddb5cc3dd146da506db7771ad5a9
https://github.com/nette/web-project/commit/62706e43cc0dd41904bbeaec2f5a34f030fab96f

**Comment by Vlczech** [comment]
(so I intercede for some note about nette/project for nette 3) :-)

**Comment by f3l1x** [comment]
It's for Nette 3, closing it here.
