### ISSUE TITLE
unexpected behaviour of ApiRequest::getParameter

### ISSUE THREAD

**Issue by khorsky** [apitte/core#138]
### Bug Description
ApiRequest::getParameter method should behave according to expected result. When using `ApiRequest::getParameter(string $name, $default = null)` you have to **know the method implementation** to find out that you have to define default value explicitly, even if it is null.

### Steps To Reproduce
```php

// given URL
// https://some.api/api/endpoint?foo=1

/**
 * @Path("/endpoint")
 */
class SomeEndpoint implements IController
{
	/**
	 * @Path("/")
	 * @Method("GET")
	 */
	public function index(ApiRequest $request, ApiResponse $response): ApiResponse
	{
		$request->getParameter('foo');	// 1
		$request->getParameter('bar');	// null expected, exception thrown
	}
}
```

### Expected Behavior
`$request->getParameter('bar');` should return null, not throw InvalidStateParameter.

**Comment by f3l1x** [comment]
Hi @khorsky. It's common pattern in Nette to have this optional parameter. I would like to keep it this way.

**Comment by f3l1x** [comment]
It would be nice when you prepare some PR with extra clarification.

**Comment by khorsky** [comment]
@f3l1x Sorry for unclear description. I've opened this issue because apitte is not behaving the nette way.

Use case: I want to get NULL as a default parameter value (no other conditions).

Nette working example ([responsible method](https://github.com/nette/application/blob/0e37ebdb4f73716388de48ccb095e49c491bf2b4/src/Application/UI/Component.php#L178)):
`$presenter->getParameter('parameter-not-set') === NULL; // true`

Apitte used as Nette is not working ([responsible conditions](https://github.com/apitte/core/blob/1d036a630127d8d1e2937b01d31f12518fc20400/src/Http/ApiRequest.php#L26)):
`$request->getParameter('parameter-not-set') === NULL;  //  InvalidStateParameter exception`

Apitte working example:
`$request->getParameter('parameter-not-set', NULL) === NULL;  // true`

In described use case, the `$default` parameter is not optional, eventhough method API says so.

**Comment by f3l1x** [comment]
Oh I see, could you please prepare a PR with nette-like solution https://github.com/nette/application/blob/0e37ebdb4f73716388de48ccb095e49c491bf2b4/src/Application/UI/Component.php#L178?

**Comment by f3l1x** [comment]
Resolved via https://github.com/apitte/core/commit/d582b3fe2b995445d55d25e94120c031b69a2850, thanks.
