### ISSUE TITLE
Refinement of the composer dependencies

### ISSUE THREAD

**Issue by jaroslavlibal** [apitte/core#148]
The newly released version 0.7 has a contributte/psr7-http-message package dependency - requires the unreleased version ~0.7.0. Either a new tag should be issued for the contributte/psr7-http-message or the contributte/psr7-http-message dependency should be updated.

The apitte/core package also depends on the nette/utils package which was released in the 3.2 version recently - this new nette/utils version is not supported in the composer.json file.

**Comment by f3l1x** [comment]
This should be fixed now.
