### ISSUE TITLE
PHP 8 annotations not supported

### ISSUE THREAD

**Issue by racinmat** [apitte/core#151]
Hi, I tried to use 
`#[Path("/")]` instead of 
```
/**
 * @Path("/")
 */
```
but Apitte complained about
```
Apitte\Core\Exception\Logical\InvalidSchemaException

@Path in "App\Controllers\HomeController" must be set.

.../Validation/ControllerPathValidation.php:14   Apitte\Core\Schema\Validation\ControllerPathValidation->validateSlashes()
.../Validator/SchemaBuilderValidator.php:22   Apitte\Core\Schema\Validation\ControllerPathValidation->validate()
.../core/src/DI/Plugin/CoreSchemaPlugin.php:155   Apitte\Core\Schema\Validator\SchemaBuilderValidator->validate()
.../core/src/DI/Plugin/CoreSchemaPlugin.php:97   Apitte\Core\DI\Plugin\CoreSchemaPlugin->validateSchema()
.../core/src/DI/Plugin/CoreSchemaPlugin.php:82   Apitte\Core\DI\Plugin\CoreSchemaPlugin->compileSchema()
.../core/src/DI/Plugin/PluginManager.php:88   Apitte\Core\DI\Plugin\CoreSchemaPlugin->beforePluginCompile()
.../apitte/core/src/DI/ApiExtension.php:62   Apitte\Core\DI\Plugin\PluginManager->beforeCompiles()
.../b5a/vendor/nette/di/src/DI/Compiler.php:259   Apitte\Core\DI\ApiExtension->beforeCompile()
.../b5a/vendor/nette/di/src/DI/Compiler.php:202   Nette\DI\Compiler->processBeforeCompile()
.../nette/di/src/DI/ContainerLoader.php:117   Nette\DI\Compiler->compile()
.../nette/di/src/DI/ContainerLoader.php:79   Nette\DI\ContainerLoader->generate()
.../nette/di/src/DI/ContainerLoader.php:44   Nette\DI\ContainerLoader->loadFile()
.../bootstrap/src/Bootstrap/Configurator.php:270   Nette\DI\ContainerLoader->load()
.../bootstrap/src/Bootstrap/Configurator.php:248   Nette\Bootstrap\Configurator->loadContainer()
/var/www/b5a/www/index.php:7   Nette\Bootstrap\Configurator->createContainer()
```
am I using it wrong, or is the new format not yet supported?
Thanks.

**Comment by f3l1x** [comment]
Hi! PHP 8 annotations are not supported right now, will be definitely in the future.

**Comment by TomasVotruba** [comment]
Just migrating projects annotations to attributes with Rector and these are the last ones.
We would use this feature too :+1:

**Comment by f3l1x** [comment]
Hi @racinmat and @TomasVotruba. More users wanted this feature, I should take a look. Thank you for pointing me.

**Comment by TomasVotruba** [comment]
Great :+1: 

Running this rule should do the work for upgrading annotations to also-attributes:
https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#doctrineannotationclasstoattributerector

**Comment by TomasVotruba** [comment]
I did similar migration for our interna lannotaitons and Doctrine annotation parser. 
Post is coming this week :) there might be some clues on how to do it.

**Comment by TomasVotruba** [comment]
This might help
https://tomasvotruba.com/blog/how-to-refactor-custom-doctrine-annotations-to-attributes

**Comment by TomasVotruba** [comment]
I'll look on it next week, the mix of annotations and attributes in our code is way too confusing :)

**Comment by TomasVotruba** [comment]
See https://github.com/apitte/core/pull/161

**Comment by TomasVotruba** [comment]
Good news :tada: 

After thorough testing and fine-tuning of order and attribute param value, we've just merged this feature to `master` :+1: 

Could you release stable verison this week so we can cleanup the ugly commit lock in composer?
