### ISSUE TITLE
RequestParameterValidation

### ISSUE THREAD

**Issue by mabar** [apitte/core#40]
- based on https://github.com/apitte/core/pull/35
- extend existing RequestParameterValidation
- check if every parameter in mask have also endpoint parameter (prevents weak-typed inputs)

**Comment by mabar** [comment]
Also document CoreSchemaPlugin and CoreServicesPlugin and make them configurable.

**Comment by f3l1x** [comment]
Please complete this issue and we will release 0.4 immediately.
