### ISSUE TITLE
CheckAuth annotation for individual methods

### ISSUE THREAD

**Issue by vylink** [apitte/core#48]
Hi,

I'd like to add some kind of annotation for individual methods in the controllers to add ability to decide if the request needs authentication header or not - ideally in middleware.

Something like this

```
/**
 * @Controller
 * @ControllerPath("/")
 */
final class HomeController extends BaseV1Controller
{
	/**
	 * @Path("/")
         * @CheckAuth <---- SOMETHING LIKE THIS
	 * @Method("GET")
	 */
	public function index(ApiRequest $request, ApiResponse $response)
	{
		return $response->withEntity(ArrayEntity::from(['data' => ['Welcome']]));
	}
}
```

Question is, how can I check if this annotation exists in the middleware?

...or, is there any way how to add "CheckAuth" just for individual methods?

**Comment by mabar** [comment]
I think you could create your own middleware for that. Use router (available as a service in DIC) to check, which endpoint will be used.
https://github.com/apitte/core/blob/master/src/Router/SimpleRouter.php

**Comment by vylink** [comment]
Hi,

thanks for quick answer. I see ... but is there any way how can I access controller method's annotations in the middleware?

**Comment by mabar** [comment]
Get endpoint from request, get handler from endpoint, get class and method, read method annotations through reflection. Thats all.
https://github.com/apitte/core/blob/master/src/Router/SimpleRouter.php#L38
https://github.com/apitte/core/blob/master/src/Schema/Endpoint.php#L128
https://github.com/apitte/core/blob/master/src/Schema/EndpointHandler.php

**Comment by f3l1x** [comment]
You can:

- decide it according to URL
- decide it according to `@Tag` annotation
- decide it according your own annotation (needs to be added to schema)

**Comment by mabar** [comment]
Btw, revert what you want. Create `@NoCheckAuth` and check all endpoints by default. It is more secure.

**Comment by vylink** [comment]
@mabar : good idea with reverting and NoCheckAuth ;)
I'm very sorry for stupid question, but how can I get router from service in DIC within the middleware?

**Comment by vylink** [comment]
@mabar  - Are you available for skype call (paid consultation) about it? I'd like to apitte for new project and I have couple of questions.

**Comment by mabar** [comment]
Are you at pehapkari.slack.com? We could talk about it at slack. https://pehapkari.herokuapp.com
