### ISSUE TITLE
request parameter types - enum, list, range

### ISSUE THREAD

**Issue by mabar** [apitte/core#49]

**Comment by mabar** [comment]
`@RequestParameter(name=foo, type=string, allowedValues=foo,bar,baz)` - for enum (just limiting scope, not really enum type)
`@RequestParameter(name=foo, type=string, acceptMultiple=true)` - for list (would return array of values)
cc @f3l1x

**Comment by mabar** [comment]
Problem with list is that it is represented in different ways, depends on a `in` parameter.
In query - `foo[]=foo&foo[]=bar&foo[]=baz`
In path - ???
In cookie - json encoded?
In header - probably multiple headers with same name?

(Note to self - check current implementation for headers - only one for `string`, multiple for `string[]`)

**Comment by lulco** [comment]
In path: coma separated? /hello/world/foo,bar,baz

**Comment by mabar** [comment]
I think there is no practical reason to support enum in path, so we don't need to worry about implementation.

**Comment by lulco** [comment]
sure :) that was my second option to tell you: do not support enum in path

**Comment by mabar** [comment]
Note to self - arrays:
- https://swagger.io/docs/specification/describing-parameters/#query-parameters
- https://swagger.io/docs/specification/serialization/

**Comment by marten-cz** [comment]
@mabar How is it with the support for the arrays? Not sure if it was planned to implement or not. Looking for string[], int[], don't need enum, but list of ids. List of objects will be nice too :) Cannot inject own validation object.
