### ISSUE TITLE
Output all error messages at once

### ISSUE THREAD

**Issue by mabar** [apitte/core#59]
Currently once a client error is found then it's immediatelly written to output.
We should e.g. validate all request parameters at once then output errors.
Validate whole request entity (and all request entities once #46 is implemented) then output errors.
Endpoints should behave the same.

Probably best would be an configurable exception, like `$clientErrorException->addError($error)`.

**Comment by f3l1x** [comment]
Lets put it on v0.5. OK?

**Comment by mabar** [comment]
Thinked about it a lot and I have new proposal.

```php
$exception = new ClientErrorException('', 404);
$exception->withMessages(['foo', 'bar', 'baz']);
```

Output would be (for default ErrorHandler and Json(Unify)Transformer
```php
[
  'status' => 'error',
  'code' => 404,
  'errors' => ['foo', 'bar', 'baz'],
  'context' => ['...'], // Not sure about context as we usually put inside only exception which should not be displayed to user
]
```

I deliberately don't use `data` key as we use currently for errors. Data will don't have different format in case of error and also it's not really needed to return only errors if an error occured.

We could in future create mechanism to add errors without throwing exception so api could work with valid and invalid data at the same time.
In current state if one of requested entities (e.g. multiple orders) failed to be processed then whole request fails.

**Comment by mabar** [comment]
Also add:

- no default or meaningful default messages for all api exceptions
- allow redefine error messages (public static variable should be enough)

**Comment by mabar** [comment]
We should also add an optional reason to errors. Oftenly error 400 could be created for many reasons and parsing error message is no-way
