### ISSUE TITLE
Prefixed annotations does not work

### ISSUE THREAD

**Issue by davidkudera** [apitte/core#6]
Hi, I tried to import annotation namespace with `Apitte\CoreAnnotation\Controller as API` and then use for example `@API\Controller()` to avoid too long `use` list in all of my controllers.

This doesn't throw any error, it only returns nothing. If I use `Apitte\CoreAnnotation\Controller\Controller()` directly everything works fine.

It would also be nice to support this because it's similar to what we're all probably using right now with Doctrine (`Doctrine\ORM\Mapping as ORM`).

**Comment by f3l1x** [comment]
Hi. Thanks for reporting. I'll test it on my PC, will let you know.

**Comment by kralmichal** [comment]
Hi, 

I think the problem is here. Nette reflection is returning the annotation as `API\Controller`.

https://github.com/apitte/core/blob/feb896b800d02a64bac4b3b609d9221e92489545/src/DI/Loader/DoctrineAnnotationLoader.php#L128


Workaround would be to modify the `acceptController` method to something like this. 

```php
if ($class->hasAnnotation('Controller') || $class->hasAnnotation('API\Controller')) return TRUE;
```

Any thoughts @f3l1x?

**Comment by f3l1x** [comment]
Thanks for the PR @kralmichal, unfortunatelly it cannot be resolved as you wrote. What about if I want to use `Apitte\CoreAnnotation\Controller as REST`? I needs deeper investigation, maybe get rid of the nette reflection and use only doctrine one?

**Comment by enumag** [comment]
Exactly. Nette reflection should not be used to detect annotation. Replace it with Docrine annotations reader.

**Comment by f3l1x** [comment]
Could you @davidkudera test it? It should be fixed in master.

**Comment by davidkudera** [comment]
Seems that it works perfectly, thank you very much 🍻
