### ISSUE TITLE
Use Tag annotation in 0.4 will cause not valid OpenApi format. 

### ISSUE THREAD

**Issue by benijo** [apitte/core#65]
I'm going from version 0.3 to version 0.4 and I found a bug in open api generation.

`OpenApiService->getOperationTags($endpoint)` should return `string[]` but it returns `object[]`.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#operation-object

![image](https://user-images.githubusercontent.com/6731626/47848731-91ddc880-ddcf-11e8-93df-c9e04048e26d.png)

I think there is a problem in `apitte/core` somewhere in `ArrayHydrator`/`ArraySerializator`/`Tag` not in `apitte/openapi`.

**Comment by mabar** [comment]
I missed that during refactoring. I will take a look at it.

**Comment by mabar** [comment]
Actually fixed in master by apitte/openapi, so closing
