### ISSUE TITLE
ClientErrorException - how to modify headers?

### ISSUE THREAD

**Issue by vylink** [apitte/core#95]
Hi,

Is it possible to modify response headers for ClientErrorException?
Error Response is not delivered to the browser because of CORS :( Any advice?

Cheers

**Comment by mabar** [comment]
From #96 I see you use ResponseDecorator. Just implement IErrorDecorator, it should be enough.
https://github.com/apitte/core/blob/master/src/Decorator/IErrorDecorator.php#L19

**Comment by vylink** [comment]
Many thanks. It works perfectly.
